-- AlterTable
ALTER TABLE `cards` ADD COLUMN `deadline` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('CARD_ASSIGNED', 'CARD_UPDATED', 'CARD_COMPLETED', 'COMMENT_ADDED', 'COMMENT_MENTION', 'SUBTASK_COMPLETED', 'PROJECT_INVITE', 'TIME_LOG_REMINDER', 'DEADLINE_APPROACHING', 'DEADLINE_OVERDUE') NOT NULL;

-- AlterTable
ALTER TABLE `projects` ADD COLUMN `deadline` DATETIME(3) NULL;
